// ============================================================
// export.ts — pure export utilities
//
// All functions are framework-free. React components call
// these; they never import React themselves.
//
// PDF generation uses dynamic import("jspdf") so the ~250 KB
// library is only loaded when the physician clicks Export PDF.
// ============================================================

import { MODEL_CONFIG } from "../config/model";
import { buildInterpretation } from "./interpretation";
import type { NomogramInputs, RiskResult } from "../types/nomogram";

// ─── ReportData ───────────────────────────────────────────────────────────────
// Single interface consumed by both clipboard and PDF paths.
// Built once, passed to either output function.
export interface ReportData {
  // Metadata
  timestamp: string;          // human-readable: "13 June 2026 · 14:32 UTC+7"
  filenameTimestamp: string;  // filename-safe:  "20260613-1432"

  // Inputs (display labels, not internal enum values)
  tumorLocationLabel: string;
  nlr: number;
  plr: number;
  nlrFormatted: string;       // "3.7"
  plrFormatted: string;       // "168"

  // Result
  probabilityPercent: string; // "34.8%"
  categoryLabel: string;      // "Intermediate"
  exploratoryNote: string;    // from MODEL_CONFIG

  // Text — identical to what the UI renders
  interpretationText: string;

  // Model
  outcome: string;
  modelType: string;
  auc: string;
  brierScore: string;
  cohortN: string;
  predictorLabels: string[];
  validationNote: string;

  // Disclaimer
  disclaimerText: string;
}

// ─── Category display label ───────────────────────────────────────────────────
const CATEGORY_LABELS: Record<string, string> = {
  low:          "Low",
  intermediate: "Intermediate",
  high:         "High",
};

// ─── buildReportData ──────────────────────────────────────────────────────────
export function buildReportData(
  inputs: NomogramInputs,
  result: RiskResult
): ReportData {
  const dn  = MODEL_CONFIG.displayNames;
  const fd  = MODEL_CONFIG.formulaDisplay;
  const md  = MODEL_CONFIG.metadata;
  const rc  = MODEL_CONFIG.riskCategories;

  // Timestamps
  const now       = new Date();
  const humanDate = now.toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });
  const timeStr   = now.toLocaleTimeString("en-GB", {
    hour: "2-digit", minute: "2-digit", hour12: false,
  });
  // UTC offset computed from Date so it reflects DST correctly at generation time.
  // Produces "UTC+7", "UTC-5", "UTC+5:30" — unambiguous for any clinical reader.
  const rawOffsetMin = -now.getTimezoneOffset();
  const absMin       = Math.abs(rawOffsetMin);
  const offsetH      = Math.floor(absMin / 60);
  const offsetM      = absMin % 60;
  const offsetSign   = rawOffsetMin >= 0 ? "+" : "-";
  const utcOffset    =
    "UTC" + offsetSign + offsetH +
    (offsetM ? ":" + String(offsetM).padStart(2, "0") : "");
  const timestamp    = `${humanDate} · ${timeStr} ${utcOffset}`;

  // Filename-safe timestamp: YYYYMMDD-HHMM
  const y  = now.getFullYear();
  const mo = String(now.getMonth() + 1).padStart(2, "0");
  const d  = String(now.getDate()).padStart(2, "0");
  const h  = String(now.getHours()).padStart(2, "0");
  const mi = String(now.getMinutes()).padStart(2, "0");
  const filenameTimestamp = `${y}${mo}${d}-${h}${mi}`;

  return {
    timestamp,
    filenameTimestamp,

    tumorLocationLabel:
      inputs.tumorLocation === "single"
        ? dn.tumorSingleSite
        : dn.tumorMultipleSites,
    nlr:          inputs.nlr,
    plr:          inputs.plr,
    nlrFormatted: inputs.nlr.toFixed(1),
    plrFormatted: String(Math.round(inputs.plr)),

    probabilityPercent: (result.probability * 100).toFixed(1) + "%",
    categoryLabel:      CATEGORY_LABELS[result.category] ?? result.category,
    exploratoryNote:    rc.exploratoryLabel,

    interpretationText: buildInterpretation(
      inputs,
      result.probability,
      result.category
    ),

    outcome:   md.outcome,
    modelType: md.modelType,
    auc:       md.auc.toFixed(3),
    brierScore: md.brierScore.toFixed(3),
    cohortN:   `n = ${md.cohortN}`,
    predictorLabels: fd.terms.map((t) => t.label),
    validationNote:
      "Internal validation only. External validation has not been performed.",

    disclaimerText:
      "For research and educational use only. This report was generated by a " +
      "computational model and does not replace clinical judgment, physician " +
      "assessment, or established diagnostic protocols. Results should be " +
      "interpreted by qualified healthcare professionals in the context of all " +
      "available clinical information.",
  };
}

// ─── buildClipboardText ───────────────────────────────────────────────────────
// Produces plain text that pastes cleanly into EHR notes and emails.
export function buildClipboardText(data: ReportData): string {
  return [
    "GASTRIC CANCER METASTASIS RISK — CALCULATION REPORT",
    "====================================================",
    "",
    `Generated: ${data.timestamp}`,
    "",
    "PATIENT PARAMETERS",
    `  Tumor Location : ${data.tumorLocationLabel}`,
    `  NLR            : ${data.nlrFormatted}`,
    `  PLR            : ${data.plrFormatted}`,
    "",
    "PREDICTED RISK",
    `  Probability    : ${data.probabilityPercent}`,
    `  Category       : ${data.categoryLabel}`,
    `  Note           : ${data.exploratoryNote}`,
    "",
    "CLINICAL INTERPRETATION",
    data.interpretationText,
    "",
    "MODEL INFORMATION",
    `  Outcome        : ${data.outcome}`,
    `  Model          : ${data.modelType}`,
    `  AUC            : ${data.auc}`,
    `  Brier Score    : ${data.brierScore}`,
    `  Cohort         : ${data.cohortN}`,
    `  Predictors     : ${data.predictorLabels.join(" · ")}`,
    `  Validation     : ${data.validationNote}`,
    "",
    "DISCLAIMER",
    data.disclaimerText,
  ].join("\n");
}

// ─── copyToClipboard ─────────────────────────────────────────────────────────
// Returns true on success, false on failure.
// Tries modern API first, falls back to execCommand for older Safari.
export async function copyToClipboard(text: string): Promise<boolean> {
  // Modern Clipboard API
  if (navigator?.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      // Fall through to legacy method
    }
  }
  // Legacy fallback (older Safari, some iOS WebViews)
  try {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.top = "-9999px";
    ta.style.left = "-9999px";
    ta.setAttribute("aria-hidden", "true");
    document.body.appendChild(ta);
    ta.focus();
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}

// ─── PDF colour palette ───────────────────────────────────────────────────────
// CSS variables are not available in jsPDF — hardcoded hex values that match
// the screen UI palette exactly.
const PDF_COLORS = {
  navyBg:        [10,  37,  64]  as [number, number, number], // #0A2540
  navyText:      [255, 255, 255] as [number, number, number],
  navySubtext:   [148, 163, 184] as [number, number, number], // text/45
  slatePrimary:  [15,  23,  42]  as [number, number, number], // #0F172A
  slateBody:     [71,  85,  105] as [number, number, number], // #475569
  slateLabel:    [148, 163, 184] as [number, number, number], // #94A3B8
  slateSurface:  [248, 250, 252] as [number, number, number], // #F8FAFC
  borderLight:   [226, 232, 240] as [number, number, number], // #E2E8F0
  amberBg:       [255, 251, 240] as [number, number, number], // #FFFBF0
  amberBorder:   [253, 230, 138] as [number, number, number], // #FDE68A
  amberText:     [146, 64,   14] as [number, number, number], // #92400E
  riskLow:       [71,  85,  105] as [number, number, number], // slate (no green)
  riskInt:       [180, 83,   9]  as [number, number, number], // #B45309
  riskHigh:      [185, 28,  28]  as [number, number, number], // #B91C1C
  footerBg:      [241, 245, 249] as [number, number, number], // #F1F5F9
  footerText:    [148, 163, 184] as [number, number, number],
} as const;

function riskColor(
  category: string
): [number, number, number] {
  if (category === "Low")          return PDF_COLORS.riskLow;
  if (category === "Intermediate") return PDF_COLORS.riskInt;
  return PDF_COLORS.riskHigh;
}

// ─── generateAndDownloadPDF ───────────────────────────────────────────────────
export async function generateAndDownloadPDF(data: ReportData): Promise<void> {
  // Lazy-load jsPDF — only downloaded when this function is first called.
  const { jsPDF } = await import("jspdf");

  const doc  = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const PW   = doc.internal.pageSize.getWidth();   // 210
  const ML   = 18; // margin left
  const MR   = 18; // margin right
  const CW   = PW - ML - MR;                       // 174 mm content width
  let   y    = 0;  // running Y cursor

  // ── Helpers ──────────────────────────────────────────────────────────────
  function setColor(c: [number,number,number]) {
    doc.setTextColor(c[0], c[1], c[2]);
  }
  function setFill(c: [number,number,number]) {
    doc.setFillColor(c[0], c[1], c[2]);
  }
  function setDraw(c: [number,number,number]) {
    doc.setDrawColor(c[0], c[1], c[2]);
  }
  function eyebrow(text: string, xPos = ML) {
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    setColor(PDF_COLORS.slateLabel);
    doc.text(text.toUpperCase(), xPos, y);
  }
  function hline(yPos: number, col = PDF_COLORS.borderLight) {
    setDraw(col);
    doc.setLineWidth(0.2);
    doc.line(ML, yPos, PW - MR, yPos);
  }
  function wrappedText(
    text: string,
    x: number,
    startY: number,
    maxWidth: number,
    lineHeight: number
  ): number {
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, startY);
    return startY + lines.length * lineHeight;
  }

  // ── 1. Header bar ─────────────────────────────────────────────────────────
  setFill(PDF_COLORS.navyBg);
  doc.rect(0, 0, PW, 20, "F");

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  setColor(PDF_COLORS.navyText);
  doc.text("Gastric Cancer Metastasis Risk Calculator", ML, 9);

  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  setColor(PDF_COLORS.navySubtext);
  doc.text("Multivariable Logistic Regression · AUC " + data.auc, ML, 14.5);

  // Research Tool badge (top-right)
  const badgeText  = "RESEARCH TOOL";
  doc.setFontSize(6.5);
  const badgeW = doc.getTextWidth(badgeText) + 6;
  const badgeX = PW - MR - badgeW;
  setDraw([148, 163, 184]);
  doc.setLineWidth(0.3);
  doc.roundedRect(badgeX, 7, badgeW, 6, 1, 1, "S");
  setColor(PDF_COLORS.navySubtext);
  doc.text(badgeText, badgeX + 3, 11.2);

  y = 26;

  // ── 2. Report timestamp ───────────────────────────────────────────────────
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  setColor(PDF_COLORS.slateLabel);
  doc.text("Report generated", ML, y);
  y += 4.5;
  doc.setFontSize(9);
  setColor(PDF_COLORS.slatePrimary);
  doc.text(data.timestamp, ML, y);
  y += 7;

  hline(y); y += 6;

  // ── 3. Patient parameters ─────────────────────────────────────────────────
  eyebrow("Patient Parameters"); y += 5.5;

  // Three tiles side by side
  const tileW  = (CW - 6) / 3;
  const tileH  = 14;
  const tiles  = [
    { label: "Tumor Location", value: data.tumorLocationLabel },
    { label: "NLR",            value: data.nlrFormatted        },
    { label: "PLR",            value: data.plrFormatted        },
  ];
  tiles.forEach((tile, i) => {
    const tx = ML + i * (tileW + 3);
    setFill(PDF_COLORS.slateSurface);
    setDraw(PDF_COLORS.borderLight);
    doc.setLineWidth(0.2);
    doc.roundedRect(tx, y, tileW, tileH, 2, 2, "FD");

    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    setColor(PDF_COLORS.slateLabel);
    doc.text(tile.label.toUpperCase(), tx + 3, y + 4.5);

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    setColor(PDF_COLORS.slatePrimary);
    doc.text(tile.value, tx + 3, y + 11);
  });
  y += tileH + 7;

  hline(y); y += 6;

  // ── 4. Predicted risk ─────────────────────────────────────────────────────
  eyebrow("Predicted Risk"); y += 5.5;

  // Large probability number
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  setColor(riskColor(data.categoryLabel));
  doc.text(data.probabilityPercent, ML, y + 10);

  // Category badge — positioned to the right of the large number
  const numWidth = doc.getTextWidth(data.probabilityPercent);
  const badgeStartX = ML + numWidth + 5;

  doc.setFontSize(8.5);
  doc.setFont("helvetica", "bold");
  setColor(riskColor(data.categoryLabel));
  doc.text(data.categoryLabel, badgeStartX, y + 4);

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  setColor(PDF_COLORS.slateLabel);
  const exLines = doc.splitTextToSize(data.exploratoryNote + ".", CW - numWidth - 8);
  doc.text(exLines, badgeStartX, y + 9);

  y += 19;
  hline(y); y += 6;

  // ── 5. Clinical interpretation ────────────────────────────────────────────
  eyebrow("Clinical Interpretation"); y += 5.5;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  setColor(PDF_COLORS.slateBody);
  y = wrappedText(data.interpretationText, ML, y, CW, 5);
  y += 6;

  hline(y); y += 6;

  // ── 6. Model information ──────────────────────────────────────────────────
  eyebrow("Model Information"); y += 5.5;

  // 6-item grid in two columns: Outcome/Model, AUC/Brier, Cohort/Validation
  const modelRows: [string, string][] = [
    ["Outcome",     data.outcome        ],
    ["Model",       data.modelType      ],
    ["AUC",         data.auc            ],
    ["Brier Score", data.brierScore     ],
    ["Cohort",      data.cohortN        ],
    ["Validation",  data.validationNote ],
  ];
  const halfCW = (CW - 4) / 2;

  modelRows.forEach(([label, value], i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const rx  = ML + col * (halfCW + 4);
    const ry  = y + row * 9;

    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    setColor(PDF_COLORS.slateLabel);
    doc.text(label, rx, ry);

    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    setColor(PDF_COLORS.slatePrimary);
    doc.text(value, rx + halfCW, ry, { align: "right", maxWidth: halfCW - 2 });

    // Hairline separators between rows (not after the last row)
    if (row < Math.ceil(modelRows.length / 2) - 1) {
      setDraw(PDF_COLORS.borderLight);
      doc.setLineWidth(0.15);
      doc.line(rx, ry + 2, rx + halfCW, ry + 2);
    }
  });

  y += Math.ceil(modelRows.length / 2) * 9 + 3;

  // Predictors — full-width row at the bottom of the model info block
  hline(y);
  y += 4;
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  setColor(PDF_COLORS.slateLabel);
  doc.text("Predictors", ML, y);
  y += 4.5;
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  setColor(PDF_COLORS.slatePrimary);
  y = wrappedText(data.predictorLabels.join("  ·  "), ML, y, CW, 4.5);
  y += 6;

  hline(y); y += 0;

  // ── 7. Disclaimer (amber block) ───────────────────────────────────────────
  const disclaimerLines = doc.setFontSize(8) &&
    doc.splitTextToSize(data.disclaimerText, CW - 4);
  const disclaimerH = disclaimerLines.length * 4.8 + 10;

  setFill(PDF_COLORS.amberBg);
  setDraw(PDF_COLORS.amberBorder);
  doc.setLineWidth(0.3);
  doc.rect(ML, y, CW, disclaimerH, "FD");

  y += 5;
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  setColor(PDF_COLORS.amberText);
  doc.text("Research and educational use only.", ML + 3, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.text(disclaimerLines, ML + 3, y);

  y += disclaimerLines.length * 4.8 + 4;

  // ── 8. Footer ─────────────────────────────────────────────────────────────
  const footerY = doc.internal.pageSize.getHeight() - 10;
  setFill(PDF_COLORS.footerBg);
  doc.rect(0, footerY - 4, PW, 14, "F");

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  setColor(PDF_COLORS.footerText);
  doc.text("Gastric Cancer Metastasis Risk Calculator", ML, footerY + 2);
  doc.text("Page 1 of 1", PW - MR, footerY + 2, { align: "right" });

  // ── Save ──────────────────────────────────────────────────────────────────
  doc.save(`gastric-metastasis-risk-${data.filenameTimestamp}.pdf`);
}
